var preloadState ={   
    //load all flgas, bitmap text, buttons
    preload: function() {
        this.bg = game.add.bitmapText(this.world.centerX,400,'myfont', "Round the World", 150);
        this.bg.anchor.setTo(0.5);
        
        this.globe = game.add.sprite(this.world.centerX,700,'globe');
        this.globe.anchor.setTo(0.5);
        
        this.loadBar = game.add.sprite(this.world.centerX,950,'loadingBar');
        this.loadBar.anchor.setTo(0.5);
        this.load.setPreloadSprite(this.loadBar);
        
        game.load.image('AF', 'assets/flags/AF.png');
        game.load.image('AX', 'assets/flags/AX.png');
        game.load.image('AL', 'assets/flags/AL.png');
        game.load.image('DZ', 'assets/flags/DZ.png');
        game.load.image('AS', 'assets/flags/AS.png');
        game.load.image('AD', 'assets/flags/AD.png');
        game.load.image('AO', 'assets/flags/AO.png');
        game.load.image('AI', 'assets/flags/AI.png');
        game.load.image('AQ', 'assets/flags/AQ.png');
        game.load.image('AG', 'assets/flags/AG.png');
        game.load.image('AR', 'assets/flags/AR.png');
        game.load.image('AM', 'assets/flags/AM.png');
        game.load.image('AW', 'assets/flags/AW.png');
        game.load.image('AU', 'assets/flags/AU.png');
        game.load.image('AT', 'assets/flags/AT.png');
        game.load.image('AZ', 'assets/flags/AZ.png');
        game.load.image('BS', 'assets/flags/BS.png');
        game.load.image('BH', 'assets/flags/BH.png');
        game.load.image('BD', 'assets/flags/BD.png');
        game.load.image('BB', 'assets/flags/BB.png');
        game.load.image('BY', 'assets/flags/BY.png');
        game.load.image('BE', 'assets/flags/BE.png');
        game.load.image('BZ', 'assets/flags/BZ.png');
        game.load.image('BJ', 'assets/flags/BJ.png');
        game.load.image('BM', 'assets/flags/BM.png');
        game.load.image('BT', 'assets/flags/BT.png');
        game.load.image('BO', 'assets/flags/BO.png');
        game.load.image('BQ', 'assets/flags/BQ.png');
        game.load.image('BA', 'assets/flags/BA.png');
        game.load.image('BW', 'assets/flags/BW.png');
        game.load.image('BV', 'assets/flags/BV.png');
        game.load.image('BR', 'assets/flags/BR.png');
        game.load.image('IO', 'assets/flags/IO.png');
        game.load.image('BN', 'assets/flags/BN.png');
        game.load.image('BG', 'assets/flags/BG.png');
        game.load.image('BF', 'assets/flags/BF.png');
        game.load.image('BI', 'assets/flags/BI.png');
        game.load.image('KH', 'assets/flags/KH.png');
        game.load.image('CM', 'assets/flags/CM.png');
        game.load.image('CA', 'assets/flags/CA.png');
        game.load.image('CV', 'assets/flags/CV.png');
        game.load.image('KY', 'assets/flags/KY.png');
        game.load.image('CF', 'assets/flags/CF.png');
        game.load.image('TD', 'assets/flags/TD.png');
        game.load.image('CL', 'assets/flags/CL.png');
        game.load.image('CN', 'assets/flags/CN.png');
        game.load.image('CX', 'assets/flags/CX.png');
        game.load.image('CC', 'assets/flags/CC.png');
        game.load.image('CO', 'assets/flags/CO.png');
        game.load.image('KM', 'assets/flags/KM.png');
        game.load.image('CG', 'assets/flags/CG.png');
        game.load.image('CD', 'assets/flags/CD.png');
        game.load.image('CK', 'assets/flags/CK.png');
        game.load.image('CR', 'assets/flags/CR.png');
        game.load.image('CI', 'assets/flags/CI.png');
        game.load.image('HR', 'assets/flags/HR.png');
        game.load.image('CU', 'assets/flags/CU.png');
        game.load.image('CW', 'assets/flags/CW.png');
        game.load.image('CY', 'assets/flags/CY.png');
        game.load.image('CZ', 'assets/flags/CZ.png');
        game.load.image('DK', 'assets/flags/DK.png');
        game.load.image('DJ', 'assets/flags/DJ.png');
        game.load.image('DM', 'assets/flags/DM.png');
        game.load.image('DO', 'assets/flags/DO.png');
        game.load.image('EC', 'assets/flags/EC.png');
        game.load.image('EG', 'assets/flags/EG.png');
        game.load.image('SV', 'assets/flags/SV.png');
        game.load.image('GQ', 'assets/flags/GQ.png');
        game.load.image('ER', 'assets/flags/ER.png');
        game.load.image('EE', 'assets/flags/EE.png');
        game.load.image('ET', 'assets/flags/ET.png');
        game.load.image('FK', 'assets/flags/FK.png');
        game.load.image('FO', 'assets/flags/FO.png');
        game.load.image('FJ', 'assets/flags/FJ.png');
        game.load.image('FI', 'assets/flags/FI.png');
        game.load.image('FR', 'assets/flags/FR.png');
        game.load.image('GF', 'assets/flags/GF.png');
        game.load.image('PF', 'assets/flags/PF.png');
        game.load.image('TF', 'assets/flags/TF.png');
        game.load.image('GA', 'assets/flags/GA.png');
        game.load.image('GM', 'assets/flags/GM.png');
        game.load.image('GE', 'assets/flags/GE.png');
        game.load.image('DE', 'assets/flags/DE.png');
        game.load.image('GH', 'assets/flags/GH.png');
        game.load.image('GI', 'assets/flags/GI.png');
        game.load.image('GR', 'assets/flags/GR.png');
        game.load.image('GL', 'assets/flags/GL.png');
        game.load.image('GD', 'assets/flags/GD.png');
        game.load.image('GP', 'assets/flags/GP.png');
        game.load.image('GU', 'assets/flags/GU.png');
        game.load.image('GT', 'assets/flags/GT.png');
        game.load.image('GG', 'assets/flags/GG.png');
        game.load.image('GN', 'assets/flags/GN.png');
        game.load.image('GW', 'assets/flags/GW.png');
        game.load.image('GY', 'assets/flags/GY.png');
        game.load.image('HT', 'assets/flags/HT.png');
        game.load.image('HM', 'assets/flags/HM.png');
        game.load.image('VA', 'assets/flags/VA.png');
        game.load.image('HN', 'assets/flags/HN.png');
        game.load.image('HK', 'assets/flags/HK.png');
        game.load.image('HU', 'assets/flags/HU.png');
        game.load.image('IS', 'assets/flags/IS.png');
        game.load.image('IN', 'assets/flags/IN.png');
        game.load.image('ID', 'assets/flags/ID.png');
        game.load.image('IR', 'assets/flags/IR.png');
        game.load.image('IQ', 'assets/flags/IQ.png');
        game.load.image('IE', 'assets/flags/IE.png');
        game.load.image('IM', 'assets/flags/IM.png');
        game.load.image('IL', 'assets/flags/IL.png');
        game.load.image('IT', 'assets/flags/IT.png');
        game.load.image('JM', 'assets/flags/JM.png');
        game.load.image('JP', 'assets/flags/JP.png');
        game.load.image('JE', 'assets/flags/JE.png');
        game.load.image('JO', 'assets/flags/JO.png');
        game.load.image('KZ', 'assets/flags/KZ.png');
        game.load.image('KE', 'assets/flags/KE.png');
        game.load.image('KI', 'assets/flags/KI.png');
        game.load.image('KP', 'assets/flags/KP.png');
        game.load.image('KR', 'assets/flags/KR.png');
        game.load.image('KW', 'assets/flags/KW.png');
        game.load.image('KG', 'assets/flags/KG.png');
        game.load.image('LA', 'assets/flags/LA.png');
        game.load.image('LV', 'assets/flags/LV.png');
        game.load.image('LB', 'assets/flags/LB.png');
        game.load.image('LS', 'assets/flags/LS.png');
        game.load.image('LR', 'assets/flags/LR.png');
        game.load.image('LY', 'assets/flags/LY.png');
        game.load.image('LI', 'assets/flags/LI.png');
        game.load.image('LT', 'assets/flags/LT.png');
        game.load.image('LU', 'assets/flags/LU.png');
        game.load.image('MO', 'assets/flags/MO.png');
        game.load.image('MK', 'assets/flags/MK.png');
        game.load.image('MG', 'assets/flags/MG.png');
        game.load.image('MW', 'assets/flags/MW.png');
        game.load.image('MY', 'assets/flags/MY.png');
        game.load.image('MV', 'assets/flags/MV.png');
        game.load.image('ML', 'assets/flags/ML.png');
        game.load.image('MT', 'assets/flags/MT.png');
        game.load.image('MH', 'assets/flags/MH.png');
        game.load.image('MQ', 'assets/flags/MQ.png');
        game.load.image('MR', 'assets/flags/MR.png');
        game.load.image('MU', 'assets/flags/MU.png');
        game.load.image('YT', 'assets/flags/YT.png');
        game.load.image('MX', 'assets/flags/MX.png');
        game.load.image('FM', 'assets/flags/FM.png');
        game.load.image('MD', 'assets/flags/MD.png');
        game.load.image('MC', 'assets/flags/MC.png');
        game.load.image('MN', 'assets/flags/MN.png');
        game.load.image('ME', 'assets/flags/ME.png');
        game.load.image('MS', 'assets/flags/MS.png');
        game.load.image('MA', 'assets/flags/MA.png');
        game.load.image('MZ', 'assets/flags/MZ.png');
        game.load.image('MM', 'assets/flags/MM.png');
        game.load.image('NA', 'assets/flags/NA.png');
        game.load.image('NR', 'assets/flags/NR.png');
        game.load.image('NP', 'assets/flags/NP.png');
        game.load.image('NL', 'assets/flags/NL.png');
        game.load.image('NC', 'assets/flags/NC.png');
        game.load.image('NZ', 'assets/flags/NZ.png');
        game.load.image('NI', 'assets/flags/NI.png');
        game.load.image('NE', 'assets/flags/NE.png');
        game.load.image('NG', 'assets/flags/NG.png');
        game.load.image('NU', 'assets/flags/NU.png');
        game.load.image('NF', 'assets/flags/NF.png');
        game.load.image('MP', 'assets/flags/MP.png');
        game.load.image('NO', 'assets/flags/NO.png');
        game.load.image('OM', 'assets/flags/OM.png');
        game.load.image('PK', 'assets/flags/PK.png');
        game.load.image('PW', 'assets/flags/PW.png');
        game.load.image('PS', 'assets/flags/PS.png');
        game.load.image('PA', 'assets/flags/PA.png');
        game.load.image('PG', 'assets/flags/PG.png');
        game.load.image('PY', 'assets/flags/PY.png');
        game.load.image('PE', 'assets/flags/PE.png');
        game.load.image('PH', 'assets/flags/PH.png');
        game.load.image('PN', 'assets/flags/PN.png');
        game.load.image('PL', 'assets/flags/PL.png');
        game.load.image('PT', 'assets/flags/PT.png');
        game.load.image('PR', 'assets/flags/PR.png');
        game.load.image('QA', 'assets/flags/QA.png');
        game.load.image('RE', 'assets/flags/RE.png');
        game.load.image('RO', 'assets/flags/RO.png');
        game.load.image('RU', 'assets/flags/RU.png');
        game.load.image('RW', 'assets/flags/RW.png');
        game.load.image('BL', 'assets/flags/BL.png');
        game.load.image('SH', 'assets/flags/SH.png');
        game.load.image('KN', 'assets/flags/KN.png');
        game.load.image('LC', 'assets/flags/LC.png');
        game.load.image('MF', 'assets/flags/MF.png');
        game.load.image('PM', 'assets/flags/PM.png');
        game.load.image('VC', 'assets/flags/VC.png');
        game.load.image('WS', 'assets/flags/WS.png');
        game.load.image('SM', 'assets/flags/SM.png');
        game.load.image('ST', 'assets/flags/ST.png');
        game.load.image('SA', 'assets/flags/SA.png');
        game.load.image('SN', 'assets/flags/SN.png');
        game.load.image('RS', 'assets/flags/RS.png');
        game.load.image('SC', 'assets/flags/SC.png');
        game.load.image('SL', 'assets/flags/SL.png');
        game.load.image('SG', 'assets/flags/SG.png');
        game.load.image('SX', 'assets/flags/SX.png');
        game.load.image('SK', 'assets/flags/SK.png');
        game.load.image('SI', 'assets/flags/SI.png');
        game.load.image('SB', 'assets/flags/SB.png');
        game.load.image('SO', 'assets/flags/SO.png');
        game.load.image('ZA', 'assets/flags/ZA.png');
        game.load.image('GS', 'assets/flags/GS.png');
        game.load.image('SS', 'assets/flags/SS.png');
        game.load.image('ES', 'assets/flags/ES.png');
        game.load.image('LK', 'assets/flags/LK.png');
        game.load.image('SD', 'assets/flags/SD.png');
        game.load.image('SR', 'assets/flags/SR.png');
        game.load.image('SJ', 'assets/flags/SJ.png');
        game.load.image('SZ', 'assets/flags/SZ.png');
        game.load.image('SE', 'assets/flags/SE.png');
        game.load.image('CH', 'assets/flags/CH.png');
        game.load.image('SY', 'assets/flags/SY.png');
        game.load.image('TW', 'assets/flags/TW.png');
        game.load.image('TJ', 'assets/flags/TJ.png');
        game.load.image('TZ', 'assets/flags/TZ.png');
        game.load.image('TH', 'assets/flags/TH.png');
        game.load.image('TL', 'assets/flags/TL.png');
        game.load.image('TG', 'assets/flags/TG.png');
        game.load.image('TK', 'assets/flags/TK.png');
        game.load.image('TO', 'assets/flags/TO.png');
        game.load.image('TT', 'assets/flags/TT.png');
        game.load.image('TN', 'assets/flags/TN.png');
        game.load.image('TR', 'assets/flags/TR.png');
        game.load.image('TM', 'assets/flags/TM.png');
        game.load.image('TC', 'assets/flags/TC.png');
        game.load.image('TV', 'assets/flags/TV.png');
        game.load.image('UG', 'assets/flags/UG.png');
        game.load.image('UA', 'assets/flags/UA.png');
        game.load.image('AE', 'assets/flags/AE.png');
        game.load.image('GB', 'assets/flags/GB.png');
        game.load.image('US', 'assets/flags/US.png');
        game.load.image('UM', 'assets/flags/UM.png');
        game.load.image('UY', 'assets/flags/UY.png');
        game.load.image('UZ', 'assets/flags/UZ.png');
        game.load.image('VU', 'assets/flags/VU.png');
        game.load.image('VE', 'assets/flags/VE.png');
        game.load.image('VN', 'assets/flags/VN.png');
        game.load.image('VG', 'assets/flags/VG.png');
        game.load.image('VI', 'assets/flags/VI.png');
        game.load.image('WF', 'assets/flags/WF.png');
        game.load.image('EH', 'assets/flags/EH.png');
        game.load.image('YE', 'assets/flags/YE.png');
        game.load.image('ZM', 'assets/flags/ZM.png');
        game.load.image('ZW', 'assets/flags/ZW.png');
        
        game.load.image('leftArrow', 'assets/images/leftArrow.png');
        game.load.image('rightArrow', 'assets/images/rightArrow.png');
        this.game.load.spritesheet('option', 'assets/images/options.png', 404,304,3);
        this.game.load.image('btFlag', 'assets/images/bt2.png');
        this.game.load.image('btBack', 'assets/images/back.png');
        this.game.load.image('btHome', 'assets/images/options.png'); 
        this.game.load.bitmapFont('myguifont', 'assets/fonts/guifont.png','assets/fonts/guifont.fnt');
        this.game.load.spritesheet('lives', 'assets/images/lives.png', 324, 68, 5);
        this.game.load.text('infoAF', 'js/countries.json ');
        
        this.game.load.audio('correct', 'assets/audio/correct.ogg');
        this.game.load.audio('wrong', 'assets/audio/wrong.ogg');
        this.game.load.audio('next', 'assets/audio/next.ogg');
        this.game.load.audio('back', 'assets/audio/back.ogg');
        this.game.load.audio('correct2', 'assets/audio/correct2.ogg');
        this.game.load.audio('click', 'assets/audio/click.ogg');
        this.game.load.audio('streak', 'assets/audio/streak.ogg');
        this.game.load.audio('won', 'assets/audio/gamewon.ogg');
        this.game.load.audio('over', 'assets/audio/gameover.ogg');
        
    },

    create: function() {
        for (var i= 0; i<5; i++){
            for (var j= 0; j<5; j++){
                console.log(''+i+''+j);
                console.log(localStorage.getItem(''+i+''+j));
            if(localStorage.getItem(''+i+''+j) == null){}
            else{
                game.global.highscore[i][j] = localStorage.getItem(''+i+''+j);
            }}
        this.state.start('menuState');
            
        
  }
}}